// APM Place 各楼层档口 —— 来源：用户上传的 2026 新整理档口位置表（1F–8F）
// 手工录入，编号为门牌号，name 为英文/罗马名，nameKo 为韩文名。

export type ApmPlaceShop = {
  floor: string; // 1F / 2F / 3F / 4F / 5F / 6F / 7F / 8F
  number: string; // 门牌号，含 "-1" "-2" 子号
  name: string;
  nameKo: string;
};

export const APM_PLACE_SHOPS: ApmPlaceShop[] = [
  // ===== 1F =====
  { floor: "1F", number: "101", name: "LUMIPLE", nameKo: "루미플" },
  { floor: "1F", number: "103", name: "hammingbird", nameKo: "허밍버드" },
  { floor: "1F", number: "105", name: "MARIEMARIE", nameKo: "마리스타일랩" },
  { floor: "1F", number: "107", name: "LE.PPL", nameKo: "르피피엘" },
  { floor: "1F", number: "109", name: "FLORAL", nameKo: "플로랄" },
  { floor: "1F", number: "110", name: "ANDE", nameKo: "안드" },
  { floor: "1F", number: "111", name: "ARBOL", nameKo: "아르볼" },
  { floor: "1F", number: "112", name: "2da", nameKo: "2다" },
  { floor: "1F", number: "114", name: "PLOVER", nameKo: "플러버" },
  { floor: "1F", number: "115", name: "latte", nameKo: "라떼" },
  { floor: "1F", number: "116", name: "light and salt", nameKo: "라이트앤솔트" },
  { floor: "1F", number: "117", name: "ROOKIE-BUD", nameKo: "루키버드" },
  { floor: "1F", number: "118", name: "AT THE BAGEL", nameKo: "엣더베이글" },
  { floor: "1F", number: "120", name: "FEBRUARY11", nameKo: "페브러리11" },
  { floor: "1F", number: "122", name: "edit", nameKo: "에디트" },
  { floor: "1F", number: "123", name: "ID", nameKo: "아이디" },
  { floor: "1F", number: "124", name: "SoF", nameKo: "소프" },
  { floor: "1F", number: "125", name: "A the A", nameKo: "에이더에이" },
  { floor: "1F", number: "126", name: "PLACOR", nameKo: "플라코르" },
  { floor: "1F", number: "133", name: "ATPZ", nameKo: "어텐션플리즈" },
  { floor: "1F", number: "135", name: "Pebble", nameKo: "페블" },
  { floor: "1F", number: "136", name: "PLAYBUTTON", nameKo: "플레이버튼" },
  { floor: "1F", number: "137", name: "Le etoile", nameKo: "에뜨왈" },
  { floor: "1F", number: "138", name: "WE ARE", nameKo: "위아" },
  { floor: "1F", number: "140", name: "X Party", nameKo: "엑스파티" },
  { floor: "1F", number: "141", name: "RIVER", nameKo: "리버" },
  { floor: "1F", number: "143", name: "TOOGOOD", nameKo: "투굿" },
  { floor: "1F", number: "145", name: "BLOSSOM", nameKo: "블러썸" },
  { floor: "1F", number: "147", name: "JADE MARKET", nameKo: "제이드 마켓" },
  { floor: "1F", number: "148", name: "LTMS", nameKo: "엘티엠에스" },
  { floor: "1F", number: "155", name: "FRENCH DOOR", nameKo: "프렌치도어" },
  { floor: "1F", number: "156", name: "Mento", nameKo: "멘토" },
  { floor: "1F", number: "157", name: "A.u.ra", nameKo: "아우라" },
  { floor: "1F", number: "159", name: "RESTYLE", nameKo: "리스타일" },
  { floor: "1F", number: "160", name: "KERRY", nameKo: "캐리" },
  { floor: "1F", number: "161", name: "ONDO", nameKo: "온도" },
  { floor: "1F", number: "162", name: "ARVE", nameKo: "아르브" },
  { floor: "1F", number: "163", name: "LEMATIN", nameKo: "르마틴" },
  { floor: "1F", number: "164", name: "Glitter", nameKo: "글리터" },
  { floor: "1F", number: "165", name: "MEMO", nameKo: "메모" },
  { floor: "1F", number: "166", name: "NEOUL", nameKo: "너울" },
  { floor: "1F", number: "167", name: "DAILY MOMENT", nameKo: "데일리 모먼트" },
  { floor: "1F", number: "168", name: "Jennie", nameKo: "제니" },
  { floor: "1F", number: "169", name: "OVU", nameKo: "오브유" },
  { floor: "1F", number: "171", name: "reirai", nameKo: "레이라이" },

  // ===== 2F =====
  { floor: "2F", number: "201", name: "EEE", nameKo: "이이이" },
  { floor: "2F", number: "202", name: "VAARA", nameKo: "바라" },
  { floor: "2F", number: "203", name: "ZITTEN", nameKo: "지튼" },
  { floor: "2F", number: "204", name: "nut", nameKo: "누트" },
  { floor: "2F", number: "205", name: "BLENDING", nameKo: "블렌딩" },
  { floor: "2F", number: "206", name: "BEFORE SUNRISE", nameKo: "비포선라이즈" },
  { floor: "2F", number: "207", name: "ORE", nameKo: "오어" },
  { floor: "2F", number: "208", name: "BERTHA 呼吸家", nameKo: "베르타" },
  { floor: "2F", number: "209", name: "GABIZON", nameKo: "가비존" },
  { floor: "2F", number: "210", name: "Napkin", nameKo: "냅킨" },
  { floor: "2F", number: "211", name: "ARCHIVE", nameKo: "아카이브" },
  { floor: "2F", number: "212", name: "MONDAY MORNING", nameKo: "먼데이모닝" },
  { floor: "2F", number: "213", name: "TWENTYFOURSEVEN", nameKo: "투웬티포세븐" },
  { floor: "2F", number: "215", name: "And more button", nameKo: "언드모어버튼" },
  { floor: "2F", number: "217", name: "HELLVETICA", nameKo: "헬베티카" },
  { floor: "2F", number: "218", name: "STATEMENT", nameKo: "스테이트먼트" },
  { floor: "2F", number: "220", name: "The water", nameKo: "더워터" },
  { floor: "2F", number: "222", name: "FURE", nameKo: "퓨레" },
  { floor: "2F", number: "224", name: "Vegetable 蔬菜家", nameKo: "베지터블" },
  { floor: "2F", number: "227", name: "pavel", nameKo: "파벨" },
  { floor: "2F", number: "235", name: "TAEJOON", nameKo: "태준" },
  { floor: "2F", number: "237", name: "LOVE PINK", nameKo: "럽핑" },
  { floor: "2F", number: "238", name: "MOSMOS", nameKo: "모스모스" },
  { floor: "2F", number: "239", name: "ONEBYTWO", nameKo: "원바이투" },
  { floor: "2F", number: "241", name: "MWE", nameKo: "뮤" },
  { floor: "2F", number: "243", name: "Remaking", nameKo: "리메이킹(어반스토)" },
  { floor: "2F", number: "248", name: "LOVEYOUSOMUCH", nameKo: "러브유쏘머치" },
  { floor: "2F", number: "249", name: "5KSEOUL", nameKo: "오케이서울" },
  { floor: "2F", number: "250", name: "KIKI", nameKo: "키키" },
  { floor: "2F", number: "251", name: "LEHNA", nameKo: "레나" },
  { floor: "2F", number: "252", name: "ANNA", nameKo: "안나" },
  { floor: "2F", number: "257", name: "Nocturnal vibes", nameKo: "녹터널바이브" },
  { floor: "2F", number: "261", name: "FANCY", nameKo: "팬시" },
  { floor: "2F", number: "262", name: "HONG.U", nameKo: "홍유" },
  { floor: "2F", number: "263", name: "MUY BIEN", nameKo: "무이비엔" },
  { floor: "2F", number: "265", name: "Magnet", nameKo: "마그넷" },
  { floor: "2F", number: "266", name: "RIBBON", nameKo: "리본" },
  { floor: "2F", number: "267", name: "NOON_D", nameKo: "눈디" },
  { floor: "2F", number: "268", name: "OPEN", nameKo: "오픈" },
  { floor: "2F", number: "269", name: "AWESOME", nameKo: "어썸" },
  { floor: "2F", number: "270", name: "Monter", nameKo: "몬떼" },
  { floor: "2F", number: "271", name: "REIZ", nameKo: "레이즈" },
  { floor: "2F", number: "272", name: "LA BLOOM", nameKo: "라블룸" },

  // ===== 3F =====
  { floor: "3F", number: "301", name: "OVER RICH", nameKo: "오버리치" },
  { floor: "3F", number: "303", name: "BUTTER", nameKo: "버터" },
  { floor: "3F", number: "304", name: "BABYTOUCH", nameKo: "베이비터치" },
  { floor: "3F", number: "305", name: "WINSOME", nameKo: "윈썸" },
  { floor: "3F", number: "306", name: "CULLUM", nameKo: "컬럼" },
  { floor: "3F", number: "307", name: "A.CES", nameKo: "에이써스" },
  { floor: "3F", number: "308", name: "Laffine", nameKo: "라피네" },
  { floor: "3F", number: "309", name: "BRUNI", nameKo: "브루니" },
  { floor: "3F", number: "310", name: "AUBE NUNT", nameKo: "오브넌트" },
  { floor: "3F", number: "311", name: "EPIC", nameKo: "에픽" },
  { floor: "3F", number: "312", name: "Garment 公鸡家", nameKo: "가먼트" },
  { floor: "3F", number: "313", name: "DELI", nameKo: "델리" },
  { floor: "3F", number: "314", name: "IMFACT", nameKo: "임팩트" },
  { floor: "3F", number: "315-1", name: "CAMEL", nameKo: "카멜" },
  { floor: "3F", number: "315-2", name: "juede", nameKo: "주에드" },
  { floor: "3F", number: "316", name: "COMBO", nameKo: "콤보" },
  { floor: "3F", number: "317", name: "PART.3", nameKo: "파트3" },
  { floor: "3F", number: "318", name: "MULCUP", nameKo: "물컵" },
  { floor: "3F", number: "319", name: "VictoriaQueen", nameKo: "빅토리아퀸" },
  { floor: "3F", number: "320", name: "HUE", nameKo: "휴" },
  { floor: "3F", number: "321", name: "OUPPT", nameKo: "아웁트" },
  { floor: "3F", number: "322", name: "NOWHERE", nameKo: "나우히어" },
  { floor: "3F", number: "323", name: "ANDYOU_EDITION", nameKo: "앤드유에디션" },
  { floor: "3F", number: "324", name: "Prima Luce", nameKo: "프리마 루체" },
  { floor: "3F", number: "326", name: "OFCEDRE", nameKo: "오프세더" },
  { floor: "3F", number: "327", name: "FEFFER", nameKo: "페퍼" },
  { floor: "3F", number: "328", name: "BOHEME", nameKo: "보엠" },
  { floor: "3F", number: "329", name: "Another Avenue", nameKo: "어나더에비뉴" },
  { floor: "3F", number: "330", name: "MERRY-J", nameKo: "메리제이" },
  { floor: "3F", number: "331", name: "Four Eight", nameKo: "포에잇" },
  { floor: "3F", number: "332", name: "THE BLACK", nameKo: "더블랙" },
  { floor: "3F", number: "333", name: "MELTED", nameKo: "멜티드" },
  { floor: "3F", number: "336", name: "BALANCE", nameKo: "발란스" },
  { floor: "3F", number: "337", name: "Arr", nameKo: "아르" },
  { floor: "3F", number: "338", name: "OLI SEOUL", nameKo: "올리서울" },
  { floor: "3F", number: "339", name: "osoo", nameKo: "오수" },
  { floor: "3F", number: "340", name: "RE:OPENING", nameKo: "리오프닝" },
  { floor: "3F", number: "341", name: "BRUSH", nameKo: "브러쉬" },
  { floor: "3F", number: "342", name: "bad calm", nameKo: "배드캄" },
  { floor: "3F", number: "343", name: "3another", nameKo: "쓰리어나더" },
  { floor: "3F", number: "344", name: "MUSE", nameKo: "뮤즈" },
  { floor: "3F", number: "345", name: "LA MINE DOR", nameKo: "라민느도르" },
  { floor: "3F", number: "346", name: "Moment", nameKo: "모먼트" },
  { floor: "3F", number: "347", name: "NYLON", nameKo: "나일론" },
  { floor: "3F", number: "348", name: "watermelon", nameKo: "워터멜론" },

  // ===== 4F =====
  { floor: "4F", number: "401", name: "Copiner", nameKo: "꼬피느" },
  { floor: "4F", number: "402", name: "UTRE", nameKo: "유트레" },
  { floor: "4F", number: "403", name: "Weave Selvage", nameKo: "위브셀비지" },
  { floor: "4F", number: "404", name: "at note", nameKo: "엣노트" },
  { floor: "4F", number: "405", name: "ridge", nameKo: "릿" },
  { floor: "4F", number: "406", name: "NOUVEAU", nameKo: "누보" },
  { floor: "4F", number: "407", name: "hemp", nameKo: "햄프" },
  { floor: "4F", number: "408", name: "avecnous", nameKo: "아베크누" },
  { floor: "4F", number: "409", name: "mimme", nameKo: "밈므" },
  { floor: "4F", number: "410", name: "mosaic", nameKo: "모자이크" },
  { floor: "4F", number: "411", name: "like_vam", nameKo: "라이크밤" },
  { floor: "4F", number: "412", name: "bethel", nameKo: "벧엘" },
  { floor: "4F", number: "413", name: "Sheer", nameKo: "시어" },
  { floor: "4F", number: "414", name: "THE NOB", nameKo: "더놉" },
  { floor: "4F", number: "415", name: "Alegre", nameKo: "알레그레" },
  { floor: "4F", number: "416", name: "THE VALUE", nameKo: "더벨류" },
  { floor: "4F", number: "417", name: "CLAFO", nameKo: "클라포" },
  { floor: "4F", number: "418", name: "moremore", nameKo: "모어모어" },
  { floor: "4F", number: "419", name: "j.shop", nameKo: "제이샵" },
  { floor: "4F", number: "420", name: "render", nameKo: "렌더" },
  { floor: "4F", number: "421", name: "bound.a", nameKo: "바운드에이" },
  { floor: "4F", number: "422", name: "Sorbet", nameKo: "소르베" },
  { floor: "4F", number: "423", name: "marke", nameKo: "마르케" },
  { floor: "4F", number: "424", name: "miniunni", nameKo: "미니언니" },
  { floor: "4F", number: "425", name: "find", nameKo: "파인" },
  { floor: "4F", number: "426", name: "softness", nameKo: "소프트너스" },
  { floor: "4F", number: "427", name: "person", nameKo: "펄슨" },
  { floor: "4F", number: "429", name: "mac", nameKo: "맥" },
  { floor: "4F", number: "430", name: "awnt", nameKo: "어원트" },
  { floor: "4F", number: "431", name: "shirring", nameKo: "샤링" },
  { floor: "4F", number: "432", name: "cestlavie", nameKo: "세라비" },
  { floor: "4F", number: "433", name: "CEDAR WOOD", nameKo: "시더우드" },
  { floor: "4F", number: "434", name: "meng", nameKo: "맹" },
  { floor: "4F", number: "436", name: "AMOUR", nameKo: "아무르" },
  { floor: "4F", number: "437", name: "seolo", nameKo: "서로" },
  { floor: "4F", number: "438", name: "No Problem", nameKo: "노프라블럼" },
  { floor: "4F", number: "439", name: "Langer", nameKo: "랑거" },
  { floor: "4F", number: "440", name: "juju", nameKo: "주주" },
  { floor: "4F", number: "441", name: "NEAR LEAP", nameKo: "니어리프" },
  { floor: "4F", number: "442", name: "novus", nameKo: "노버스" },
  { floor: "4F", number: "443", name: "URBANE", nameKo: "어베인" },
  { floor: "4F", number: "444", name: "amood", nameKo: "어무드" },
  { floor: "4F", number: "445", name: "gilli", nameKo: "질리" },
  { floor: "4F", number: "446", name: "EYEL", nameKo: "이엘" },
  { floor: "4F", number: "447", name: "bene", nameKo: "베네" },
  { floor: "4F", number: "448", name: "oui", nameKo: "오유아이" },

  // ===== 5F =====
  { floor: "5F", number: "501", name: "eter", nameKo: "이터" },
  { floor: "5F", number: "502-1", name: "Ripple", nameKo: "리플" },
  { floor: "5F", number: "502-2", name: "BANUL", nameKo: "밴얼" },
  { floor: "5F", number: "503-1", name: "logon", nameKo: "로그온" },
  { floor: "5F", number: "503-2", name: "JUPITER", nameKo: "주피터" },
  { floor: "5F", number: "504", name: "gallery", nameKo: "갤러리" },
  { floor: "5F", number: "505", name: "1968", nameKo: "일구육팔" },
  { floor: "5F", number: "506", name: "VAULT", nameKo: "볼트" },
  { floor: "5F", number: "507", name: "GRADE", nameKo: "그레이드" },
  { floor: "5F", number: "508-1", name: "special", nameKo: "스페셜" },
  { floor: "5F", number: "508-2", name: "NAVE", nameKo: "네이브" },
  { floor: "5F", number: "509", name: "Blue ID", nameKo: "블루아이디" },
  { floor: "5F", number: "510-1", name: "Cream", nameKo: "크림" },
  { floor: "5F", number: "510-2", name: "SANTAL", nameKo: "상탈" },
  { floor: "5F", number: "512-1", name: "SELECT MARKET", nameKo: "셀렉트마켓" },
  { floor: "5F", number: "512-2", name: "taupe", nameKo: "토프" },
  { floor: "5F", number: "513", name: "washingroom", nameKo: "워싱룸" },
  { floor: "5F", number: "514", name: "ANOU", nameKo: "아누" },
  { floor: "5F", number: "515-1", name: "more than", nameKo: "모어댄" },
  { floor: "5F", number: "515-2", name: "ABLE", nameKo: "에이블" },
  { floor: "5F", number: "516", name: "GRAYMELLOW", nameKo: "그레이멜로우" },
  { floor: "5F", number: "517", name: "OUTFIT", nameKo: "아웃핏" },
  { floor: "5F", number: "518", name: "YOUR", nameKo: "유어" },
  { floor: "5F", number: "519", name: "AGO", nameKo: "아고" },
  { floor: "5F", number: "520", name: "MYNAMEIS", nameKo: "마이네임이즈" },
  { floor: "5F", number: "521", name: "Lookk", nameKo: "루크" },
  { floor: "5F", number: "522", name: "The sand", nameKo: "더샌드" },
  { floor: "5F", number: "522-1", name: "VIBELLE", nameKo: "비벨르" },
  { floor: "5F", number: "522-2", name: "OKI", nameKo: "오키" },
  { floor: "5F", number: "523", name: "Jane Birkin", nameKo: "제인버킨" },
  { floor: "5F", number: "525-1", name: "ANOVE", nameKo: "언오브" },
  { floor: "5F", number: "525-2", name: "FAVOR", nameKo: "페이버" },

  // ===== 6F =====
  { floor: "6F", number: "601", name: "JKICHI", nameKo: "제이키치" },
  { floor: "6F", number: "602-1", name: "MYDRESS", nameKo: "마이드레스" },
  { floor: "6F", number: "602-2", name: "Neroli 36", nameKo: "네로리36" },
  { floor: "6F", number: "603-1", name: "tomgirl", nameKo: "톰걸" },
  { floor: "6F", number: "603-2", name: "AFTERNOON", nameKo: "에프터눈" },
  { floor: "6F", number: "604", name: "BINVS", nameKo: "빈어스" },
  { floor: "6F", number: "605-1", name: "MOHHE", nameKo: "모흐" },
  { floor: "6F", number: "605-2", name: "PROJECT WAVE", nameKo: "프로젝트웨이브" },
  { floor: "6F", number: "606", name: "STAGE", nameKo: "스테이지" },
  { floor: "6F", number: "607-1", name: "UNICO", nameKo: "우니코" },
  { floor: "6F", number: "607-2", name: "LEWIN", nameKo: "르윈" },
  { floor: "6F", number: "608", name: "De VENTI", nameKo: "드벤티" },
  { floor: "6F", number: "609", name: "BPLAN", nameKo: "비플랜" },
  { floor: "6F", number: "610-1", name: "The ey'l", nameKo: "더에일" },
  { floor: "6F", number: "610-2", name: "PLAM", nameKo: "플램" },
  { floor: "6F", number: "611", name: "MADE", nameKo: "메이드" },
  { floor: "6F", number: "612-1", name: "vive", nameKo: "비브" },
  { floor: "6F", number: "612-2", name: "PITA", nameKo: "피타" },
  { floor: "6F", number: "613-1", name: "LEFANCY", nameKo: "르팬시" },
  { floor: "6F", number: "613-2", name: "chav", nameKo: "차브" },
  { floor: "6F", number: "614-1", name: "baguette", nameKo: "바게트" },
  { floor: "6F", number: "614-2", name: "MiXXiN", nameKo: "믹스인" },
  { floor: "6F", number: "615", name: "unbound", nameKo: "언바운드" },
  { floor: "6F", number: "616", name: "OFNOTE", nameKo: "오브노트" },
  { floor: "6F", number: "616-1", name: "Three march", nameKo: "쓰리마치" },
  { floor: "6F", number: "616-2", name: "bes", nameKo: "베스" },
  { floor: "6F", number: "617", name: "HONG", nameKo: "홍" },
  { floor: "6F", number: "619", name: "MUTE", nameKo: "뮤트" },
  { floor: "6F", number: "620", name: "Maison Staff", nameKo: "메종스텝" },
  { floor: "6F", number: "621-1", name: "F15ty", nameKo: "15ty 피프티" },
  { floor: "6F", number: "621-2", name: "Brick Lane", nameKo: "브릭레인" },
  { floor: "6F", number: "622", name: "6pence", nameKo: "식스틴" },
  { floor: "6F", number: "623", name: "WIDA", nameKo: "위다" },

  // ===== 7F =====
  { floor: "7F", number: "701", name: "G", nameKo: "지" },
  { floor: "7F", number: "702-1", name: "daily jud", nameKo: "데일리주드" },
  { floor: "7F", number: "702-2", name: "LOW MOMENT", nameKo: "로우모먼트" },
  { floor: "7F", number: "703", name: "eoob", nameKo: "이우브" },
  { floor: "7F", number: "704-1", name: "cici", nameKo: "씨씨" },
  { floor: "7F", number: "705", name: "ICON", nameKo: "아이콘" },
  { floor: "7F", number: "705-1", name: "Repeller", nameKo: "리펠러" },
  { floor: "7F", number: "705-2", name: "DH", nameKo: "디에이치" },
  { floor: "7F", number: "706", name: "FoseT", nameKo: "포셋" },
  { floor: "7F", number: "707", name: "Jerry hall", nameKo: "제리홀" },
  { floor: "7F", number: "708-1", name: "LUMEN", nameKo: "루먼" },
  { floor: "7F", number: "708-2", name: "Fabric", nameKo: "패브릭" },
  { floor: "7F", number: "709", name: "mushroom", nameKo: "머쉬룸" },
  { floor: "7F", number: "710", name: "TOP DRESSING", nameKo: "탑드레싱" },
  { floor: "7F", number: "711-1", name: "FORMING", nameKo: "포밍" },
  { floor: "7F", number: "711-2", name: "WRITTEN BY", nameKo: "리튼바이" },
  { floor: "7F", number: "712-1", name: "EDITION", nameKo: "에디션" },
  { floor: "7F", number: "712-2", name: "BLANC", nameKo: "블랑" },
  { floor: "7F", number: "713-1", name: "MARAN", nameKo: "마란" },
  { floor: "7F", number: "713-2", name: "lucy salon", nameKo: "루씨쌀롱" },
  { floor: "7F", number: "714", name: "Bwithu", nameKo: "비위드유" },
  { floor: "7F", number: "715", name: "Hertz", nameKo: "헤르츠" },
  { floor: "7F", number: "716-1", name: "MER", nameKo: "메르" },
  { floor: "7F", number: "716-2", name: "BEENS", nameKo: "빈스" },
  { floor: "7F", number: "717", name: "PLUS HONG", nameKo: "플러스홍" },
  { floor: "7F", number: "718-1", name: "Rich Sister", nameKo: "리치시스터" },
  { floor: "7F", number: "718-2", name: "NOTTINGHAM", nameKo: "노팅엄" },
  { floor: "7F", number: "719", name: "Room K", nameKo: "룸케이" },
  { floor: "7F", number: "720", name: "ACKER", nameKo: "에이커" },
  { floor: "7F", number: "721", name: "UNDER KEY", nameKo: "언더키" },
  { floor: "7F", number: "722", name: "HAUTTE", nameKo: "하우트" },
  { floor: "7F", number: "723-2", name: "TIZZI", nameKo: "티지" },
  { floor: "7F", number: "724", name: "REPERTORY", nameKo: "레퍼토리" },
  { floor: "7F", number: "725", name: "set-pz", nameKo: "셋피젯트" },
  { floor: "7F", number: "726", name: "LOVER MOMENT", nameKo: "러브모먼트" },

  // ===== 8F =====
  { floor: "8F", number: "801", name: "Thore", nameKo: "띠오르" },
  { floor: "8F", number: "802", name: "MAINT", nameKo: "마인트" },
  { floor: "8F", number: "803-1", name: "MATIERE", nameKo: "마티에르" },
  { floor: "8F", number: "803-2", name: "ARTE", nameKo: "아르테" },
  { floor: "8F", number: "804", name: "HELDER", nameKo: "더헬더" },
  { floor: "8F", number: "805", name: "GATELESS", nameKo: "게이트리스" },
  { floor: "8F", number: "806", name: "2ndk", nameKo: "세컨케이" },
  { floor: "8F", number: "807", name: "tarabymotion", nameKo: "타라바이모션" },
  { floor: "8F", number: "808", name: "LIVE AID", nameKo: "라이브에이드" },
  { floor: "8F", number: "809", name: "ITZEL", nameKo: "이젤" },
  { floor: "8F", number: "810", name: "Herish", nameKo: "헤리쉬" },
  { floor: "8F", number: "811", name: "sunder market", nameKo: "썬더마켓" },
  { floor: "8F", number: "812", name: "GVR Company", nameKo: "지브이알컴퍼니" },
  { floor: "8F", number: "813", name: "chapter", nameKo: "챕터" },
  { floor: "8F", number: "814", name: "MURMUR", nameKo: "머멀" },
  { floor: "8F", number: "815", name: "POUCH", nameKo: "파우치" },
  { floor: "8F", number: "816", name: "BROWNS", nameKo: "브라운스" },
  { floor: "8F", number: "817", name: "credito", nameKo: "크레디토" },
  { floor: "8F", number: "818", name: "FORM", nameKo: "폼" },
];

// 转换为统一 Shop 结构（供档口管理列表复用）
import type { Shop } from "./mock-data";
export const APM_PLACE_AS_SHOPS: Shop[] = APM_PLACE_SHOPS.map((s) => ({
  id: `apmplace-${s.floor}-${s.number}`,
  name: s.name,
  nameKo: s.nameKo,
  building: "APM Place",
  floor: s.floor,
  position: s.number,
  tags: [],
  minOrderQty: 2,
  cover: `https://picsum.photos/seed/apmplace-${s.floor}-${s.number}/320/200`,
  productCount: 0,
}));