// Auto-extracted from apm视频2.mp4 via ffmpeg + tesseract(kor+eng)
// 部分 OCR 结果不完美，请以「uncertain: true」标记的条目为准手动核对。

export type ApmShop = {
  floor: string; // B1 / 1F / 3F / 4F / 5F / 6F / 7F
  number: number; // 户号
  name: string; // 韩文 / 英文原名
  uncertain?: boolean;
};

export const APM_SHOPS: ApmShop[] = [
  { floor: "B1", number: 2, name: "글 래드 썸 (9 ㄴ ㅁ SOME)" },
  { floor: "B1", number: 3, name: "gentle.b 젠 틀 비" },
  { floor: "B1", number: 4, name: "00006 앤 코드" },
  { floor: "B1", number: 5, name: "아 몬 드 페페 ALMOND PEPE" },
  { floor: "B1", number: 6, name: "코 멜 리" },
  { floor: "B1", number: 7, name: "PAPER MOON 페 이 퍼 문" },
  { floor: "B1", number: 8, name: "글 로 우 앤 님 프" },
  { floor: "B1", number: 10, name: "paperpool 페 이 퍼 풀" },
  { floor: "B1", number: 12, name: "제 이 피 크" },
  { floor: "B1", number: 13, name: "THE PLAN 더 플 랜" },
  { floor: "B1", number: 14, name: "a point 01 立 94 曰" },
  { floor: "B1", number: 15, name: "hebon 헤 본" },
  { floor: "B1", number: 17, name: "어 웨 어" },
  { floor: "B1", number: 18, name: "블 랙 프 라 이 데 이 (BlackFriday﹚" },
  { floor: "B1", number: 19, name: "먼 로" },
  { floor: "B1", number: 20, name: "에 이 미 그 레 이 스" },
  { floor: "B1", number: 21, name: "러 브 마 이 산 타" },
  { floor: "B1", number: 22, name: "object(LEHE)" },
  { floor: "B1", number: 23, name: "breathe(aalE﹚" },
  { floor: "B1", number: 24, name: "더 세 컨 그 로 우" },
  { floor: "B1", number: 25, name: "앤 드 테 라 스" },
  { floor: "B1", number: 26, name: "riveroom 리 버 룸" },
  { floor: "B1", number: 27, name: "트루" },
  { floor: "B1", number: 28, name: "레 이 크 ( ㄴ 싸 <6)" },
  { floor: "B1", number: 30, name: "까 1651Ｌ 더 실" },
  { floor: "B1", number: 31, name: "너 트 플 랜" },
  { floor: "B1", number: 32, name: "Ann Margret 앤 마 그 렛" },
  { floor: "B1", number: 33, name: "언 앤 써 드 미 스 테 리" },
  { floor: "B1", number: 35, name: "plat 플 랫" },
  { floor: "B1", number: 36, name: "43\\\\/( 네 이 비 )", uncertain: true },
  { floor: "B1", number: 37, name: "테 이 크 유 얼 타 임" },
  { floor: "B1", number: 38, name: "there 데 어" },
  { floor: "B1", number: 39, name: "stainless 스 테 인 리 스" },
  { floor: "B1", number: 40, name: "60000( 코 모 )" },
  { floor: "B1", number: 41, name: "로 가 든" },
  { floor: "B1", number: 42, name: "모 이 블 레 moible" },
  { floor: "B1", number: 43, name: "Recovera| 刃 H", uncertain: true },
  { floor: "B1", number: 44, name: "OUTRENE(RE2L)" },
  { floor: "B1", number: 45, name: "이 르 비 엔" },
  { floor: "B1", number: 46, name: "브 로 트" },
  { floor: "B1", number: 47, name: "le jardinet (&)" },
  { floor: "B1", number: 48, name: "세 니 크" },
  { floor: "B1", number: 49, name: "THECAMELC{7}%" },
  { floor: "B1", number: 50, name: "마 드 모 아 젤" },
  { floor: "B1", number: 51, name: "림 림 림" },
  { floor: "B1", number: 52, name: "project view 프 로 젝 트 뷰" },
  { floor: "B1", number: 53, name: "heyjude 헤 이 쥬 드" },
  { floor: "B1", number: 54, name: "velvetunderground 벨 벳 언 더 그 라 운 드" },
  { floor: "B1", number: 55, name: "verveine 버 베 인" },
  { floor: "B1", number: 57, name: "드 레스 룸" },
  { floor: "B1", number: 58, name: "애 프 터 글 로 우" },
  { floor: "B1", number: 59, name: "better(tH|2{)", uncertain: true },
  { floor: "B1", number: 60, name: "모 아 니" },
  { floor: "B1", number: 61, name: "오 유 에 스" },
  { floor: "B1", number: 62, name: "ROMANTICIZE 로 맨 티 사 이 즈" },
  { floor: "B1", number: 63, name: "FORTAPE ( 포 테 이 프 )" },
  { floor: "2F", number: 2, name: "플 레 이 트" },
  { floor: "2F", number: 5, name: "리 피" },
  { floor: "2F", number: 6, name: "16356 르 바 즈" },
  { floor: "2F", number: 7, name: "리 아 이 콘" },
  { floor: "2F", number: 8, name: "1 旭 老 (vunbail" },
  { floor: "2F", number: 9, name: "러 브 로 지" },
  { floor: "2F", number: 10, name: "mondaytosunday 먼 데 이 투 썬 데 이" },
  { floor: "2F", number: 11, name: "DARAK 다 락" },
  { floor: "2F", number: 12, name: "이 프 하 우스" },
  { floor: "2F", number: 13, name: "벨 류 어 블 valuable" },
  { floor: "2F", number: 14, name: "다 에 프 에 프", uncertain: true },
  { floor: "2F", number: 15, name: "TASTE 테 이 스 트" },
  { floor: "2F", number: 16, name: "차 이 ( 아 26)" },
  { floor: "2F", number: 17, name: "아 워 (000)" },
  { floor: "2F", number: 18, name: "바 이 보 미" },
  { floor: "2F", number: 19, name: "레 거 시" },
  { floor: "2F", number: 20, name: "PHILO ( 필 로 )" },
  { floor: "2F", number: 22, name: "200 G" },
  { floor: "2F", number: 23, name: "AHAIIO" },
  { floor: "2F", number: 24, name: "아 키" },
  { floor: "2F", number: 25, name: "DIEDI(MEET ME)" },
  { floor: "2F", number: 26, name: "러 브 풀" },
  { floor: "2F", number: 28, name: "더 레 스 트" },
  { floor: "2F", number: 29, name: "노 피 베" },
  { floor: "2F", number: 30, name: "04656( 누 즈 )" },
  { floor: "2F", number: 31, name: "첼 리" },
  { floor: "2F", number: 32, name: "\\/6『66038( 버 베 나 )", uncertain: true },
  { floor: "2F", number: 33, name: "오 비 르" },
  { floor: "2F", number: 34, name: "LE OVE 르 오 브" },
  { floor: "2F", number: 35, name: "Mui 무 이" },
  { floor: "2F", number: 38, name: "ㄴ 98080 로 그 로 드" },
  { floor: "2F", number: 40, name: "merciLINDA 메 르 시 린다" },
  { floor: "2F", number: 41, name: "셀 러 브 리 티" },
  { floor: "2F", number: 42, name: "MINIMUZE 미 니 뮤 즈" },
  { floor: "2F", number: 43, name: "페 이 보 릿 ( 페 이 브 )" },
  { floor: "2F", number: 44, name: "^ 이 46( 에 크 미 )" },
  { floor: "2F", number: 45, name: "로 픈" },
  { floor: "2F", number: 46, name: "뮤 르" },
  { floor: "2F", number: 47, name: "AFLAN 에 이 플 랜" },
  { floor: "2F", number: 48, name: "주 식 회 사 버 킨 컴 퍼 니" },
  { floor: "2F", number: 49, name: "one week by 00115" },
  { floor: "2F", number: 51, name: "@ 映 (ONL﹚" },
  { floor: "2F", number: 52, name: "FLAT 喬 同" },
  { floor: "2F", number: 53, name: "쏘 베" },
  { floor: "2F", number: 54, name: "로 우 하 우스" },
  { floor: "2F", number: 55, name: "옵 세 스" },
  { floor: "2F", number: 56, name: "刈 同 全" },
  { floor: "2F", number: 59, name: "W 300 J" },
  { floor: "2F", number: 60, name: "poster 포 스 터" },
  { floor: "2F", number: 61, name: "앤 더" },
  { floor: "2F", number: 63, name: "Sendtwo" },
  { floor: "3F", number: 4, name: "asome 어 썸" },
  { floor: "3F", number: 5, name: "파 도" },
  { floor: "3F", number: 6, name: "!/900 하 이 얀" },
  { floor: "3F", number: 7, name: "앤 유 브 라운" },
  { floor: "3F", number: 8, name: "6010 볼 드" },
  { floor: "3F", number: 9, name: "바 넬" },
  { floor: "3F", number: 10, name: "0 殳" },
  { floor: "3F", number: 11, name: "스 파 게 티" },
  { floor: "3F", number: 12, name: "TAKE TEE 테 이 크 티" },
  { floor: "3F", number: 13, name: "비 엔 가 더" },
  { floor: "3F", number: 14, name: "헤 이 즈" },
  { floor: "3F", number: 17, name: "€21 (villabutton)" },
  { floor: "3F", number: 18, name: "REY" },
  { floor: "3F", number: 20, name: "아 레" },
  { floor: "3F", number: 21, name: "포 터" },
  { floor: "3F", number: 24, name: "하 우스" },
  { floor: "3F", number: 25, name: "타 프 타" },
  { floor: "3F", number: 26, name: "베 르 니 먼트" },
  { floor: "3F", number: 28, name: "플 랫 가 든" },
  { floor: "3F", number: 30, name: "eggplant 에 그 플 랜 트" },
  { floor: "3F", number: 31, name: "하 우 스 오 브" },
  { floor: "3F", number: 32, name: "howff ( 하 우 프 )" },
  { floor: "3F", number: 33, name: "아 인 스 & 오 즈" },
  { floor: "3F", number: 34, name: "플 레 저 PLEASURE" },
  { floor: "3F", number: 36, name: "AUBE(2E)" },
  { floor: "3F", number: 37, name: "yes Q 內" },
  { floor: "3F", number: 38, name: "fre 프 레" },
  { floor: "3F", number: 41, name: "cobaltblue 코 발 트 블 루" },
  { floor: "3F", number: 43, name: "브 로 콜 리 샐 러 드" },
  { floor: "3F", number: 44, name: "#S0}2 (SOLD OUT)" },
  { floor: "3F", number: 46, name: "코 젯" },
  { floor: "3F", number: 47, name: "오 퍼" },
  { floor: "3F", number: 49, name: "10\\ 플 로 우", uncertain: true },
  { floor: "3F", number: 50, name: "플 랫 오기" },
  { floor: "3F", number: 51, name: "센 치 미 터 07" },
  { floor: "3F", number: 53, name: "먼 셀 MUNSELL" },
  { floor: "3F", number: 56, name: "리 시 드 (leeseed)" },
  { floor: "3F", number: 57, name: "巹 合 工 (flaunt﹚" },
  { floor: "3F", number: 58, name: "스 르 트 트" },
  { floor: "3F", number: 59, name: "매 그" },
  { floor: "4F", number: 2, name: "scope 28" },
  { floor: "4F", number: 3, name: "MARGARET 마 가 렛" },
  { floor: "4F", number: 4, name: "Authentic 어 센 틱 서 울" },
  { floor: "4F", number: 5, name: "XERON 제 론" },
  { floor: "4F", number: 6, name: "우기" },
  { floor: "4F", number: 7, name: "Depth®A" },
  { floor: "4F", number: 9, name: "로 컬" },
  { floor: "4F", number: 10, name: "Revere(2|H]|0{)", uncertain: true },
  { floor: "4F", number: 11, name: "riplej 至 z| 善 刈 0", uncertain: true },
  { floor: "4F", number: 12, name: "디 디 엠 익 스 프 레스" },
  { floor: "4F", number: 13, name: "Item planner 아 이 템 플 래 너" },
  { floor: "4F", number: 14, name: "0640( 디 어 )" },
  { floor: "4F", number: 15, name: "vampire weekend 뱀 파 이어 위 켄 드" },
  { floor: "4F", number: 17, name: "온 베 일" },
  { floor: "4F", number: 20, name: "0860 오 레 오" },
  { floor: "4F", number: 21, name: "high five 하 이 파 이 브" },
  { floor: "4F", number: 22, name: "22H0{(glamour)" },
  { floor: "4F", number: 23, name: "PLUSB2HIYA(E2{A823|0})", uncertain: true },
  { floor: "4F", number: 24, name: "크 런 키 유 스" },
  { floor: "4F", number: 25, name: "Banya in the tree 반 야 인 더 트 리" },
  { floor: "4F", number: 26, name: "D|2}X|(MIRAGE)", uncertain: true },
  { floor: "4F", number: 28, name: "MEAN ( 민 )" },
  { floor: "4F", number: 29, name: "앤 드비" },
  { floor: "4F", number: 30, name: "히 스 토리 hestory" },
  { floor: "4F", number: 31, name: "60644 에 덴" },
  { floor: "4F", number: 32, name: "gamble( 刪 旱 ﹚" },
  { floor: "4F", number: 34, name: "NOON AND DAWN 눈 앤 던" },
  { floor: "4F", number: 36, name: "라 이 즈 (312)" },
  { floor: "4F", number: 37, name: "YE| 3 (VENTIQUE)", uncertain: true },
  { floor: "4F", number: 38, name: "251 studio 이 에 스 일 스 튜 디 오" },
  { floor: "4F", number: 39, name: "바 론" },
  { floor: "4F", number: 40, name: "「3\\ 로 우", uncertain: true },
  { floor: "4F", number: 43, name: "cooper 쿠 퍼" },
  { floor: "4F", number: 44, name: "spector 스 펙 터" },
  { floor: "4F", number: 47, name: "웰던 well 00076" },
  { floor: "4F", number: 48, name: "\\460(0( 멘 토 )", uncertain: true },
  { floor: "4F", number: 49, name: "아 스 노 핏 (asnofit)" },
  { floor: "4F", number: 50, name: "MEJOR | 天 罠", uncertain: true },
  { floor: "4F", number: 52, name: "ALLWAYS 界 剌 0| 夯", uncertain: true },
  { floor: "4F", number: 53, name: "오 디 너 리 ( 크 래 커 )" },
  { floor: "4F", number: 55, name: "J2tA grass" },
  { floor: "4F", number: 57, name: "콜 키 지" },
  { floor: "4F", number: 60, name: "레 이건 raygun" },
  { floor: "4F", number: 61, name: "MAIDEN 메 이 든" },
  { floor: "4F", number: 62, name: "원 포 인 트 (OnePoint﹚" },
  { floor: "4F", number: 63, name: "001 도 트" },
  { floor: "5F", number: 4, name: "DOVER ( 도 버 )" },
  { floor: "5F", number: 5, name: "솔 트 에 비 뉴 salt avenue" },
  { floor: "5F", number: 6, name: "buffett 버 핏" },
  { floor: "5F", number: 7, name: "파 틴" },
  { floor: "5F", number: 8, name: "리 펜 (RIPEN)" },
  { floor: "5F", number: 9, name: "주 식 회 사 가 먼 츠" },
  { floor: "5F", number: 10, name: "이 스 트 하 우스" },
  { floor: "5F", number: 11, name: "제 이 앤 피" },
  { floor: "5F", number: 12, name: "팬 츠 하 우스" },
  { floor: "5F", number: 14, name: "엠 알" },
  { floor: "5F", number: 15, name: "패 러 다임" },
  { floor: "5F", number: 16, name: "MOLE(2:8)" },
  { floor: "5F", number: 17, name: "마 스 피 플" },
  { floor: "5F", number: 19, name: "pioneer 파 이 오 니 아" },
  { floor: "5F", number: 20, name: "支 霍 howell" },
  { floor: "5F", number: 21, name: "利 咐 veil" },
  { floor: "5F", number: 22, name: "기 요" },
  { floor: "5F", number: 25, name: "챔 프" },
  { floor: "5F", number: 26, name: "노 크" },
  { floor: "5F", number: 27, name: "EARN 언" },
  { floor: "5F", number: 28, name: "IDUNO|E", uncertain: true },
  { floor: "5F", number: 30, name: "페 퍼" },
  { floor: "5F", number: 31, name: "오 아 시스" },
  { floor: "5F", number: 33, name: "더 크 로 스" },
  { floor: "5F", number: 34, name: "EJUN(0|Z)", uncertain: true },
  { floor: "5F", number: 37, name: "BOWL( 28 )" },
  { floor: "5F", number: 39, name: "A rex" },
  { floor: "5F", number: 40, name: "디 드" },
  { floor: "5F", number: 41, name: "포스" },
  { floor: "5F", number: 42, name: "이 지" },
  { floor: "5F", number: 43, name: "타코" },
  { floor: "5F", number: 44, name: "데 님 홀 릭" },
  { floor: "5F", number: 45, name: "分 寸 ipeacock﹚" },
  { floor: "5F", number: 46, name: "吳 ﹤ DUDE" },
  { floor: "5F", number: 47, name: "4080×( 노 박 스 )" },
  { floor: "5F", number: 48, name: "웨 스 트" },
  { floor: "5F", number: 49, name: "안 도" },
  { floor: "5F", number: 50, name: "Kirin(?|2!)", uncertain: true },
  { floor: "5F", number: 52, name: "HERTZ 헤 르 츠" },
  { floor: "5F", number: 53, name: "페 퍼" },
  { floor: "5F", number: 54, name: "더 즈 버 프" },
  { floor: "5F", number: 55, name: "KONK" },
  { floor: "5F", number: 58, name: "591 사 이" },
  { floor: "5F", number: 59, name: "20{(roar)" },
  { floor: "5F", number: 60, name: "서 블 러 메 이 션" },
  { floor: "5F", number: 61, name: "1306 라 네" },
  { floor: "6F", number: 3, name: "answer 앤 써" },
  { floor: "6F", number: 5, name: "디 세 컨" },
  { floor: "6F", number: 6, name: "탭 탭 탭" },
  { floor: "6F", number: 7, name: "bro 브로" },
  { floor: "6F", number: 8, name: "H draw ( 에 이 치 드 로 우 )" },
  { floor: "6F", number: 9, name: "코 지 브 라운" },
  { floor: "6F", number: 10, name: "REMAIN 리 메인" },
  { floor: "6F", number: 11, name: "W&PHOUSE ( 하 우 스 )" },
  { floor: "6F", number: 13, name: "오 션 (00630)" },
  { floor: "6F", number: 15, name: "라토" },
  { floor: "6F", number: 17, name: "(#) 해 시 태 그" },
  { floor: "6F", number: 18, name: "pulse 펄 스" },
  { floor: "6F", number: 19, name: "엔 트 럴" },
  { floor: "6F", number: 20, name: "MOOD 무 드" },
  { floor: "6F", number: 21, name: "고 고 메 이 슨" },
  { floor: "6F", number: 22, name: "마 우 네" },
  { floor: "6F", number: 23, name: "19905( 구 공 에 스 )" },
  { floor: "6F", number: 24, name: "주 식 회 사 아 케 이 드 랩 스" },
  { floor: "6F", number: 25, name: "56601 시 옷" },
  { floor: "6F", number: 26, name: "데 저 트" },
  { floor: "6F", number: 27, name: "디 자 인 바 이 영 민" },
  { floor: "6F", number: 29, name: "바 이 스" },
  { floor: "6F", number: 30, name: "OFFER 오 퍼" },
  { floor: "6F", number: 31, name: "令 刈 D 以 (supermarket﹚" },
  { floor: "6F", number: 32, name: "58( 스 타 일 봉 ) 에 스 비" },
  { floor: "6F", number: 33, name: "LOUS 러 스" },
  { floor: "6F", number: 36, name: "ROA 20}" },
  { floor: "6F", number: 37, name: "KKUKKU j 衍" },
  { floor: "6F", number: 38, name: "레 이 브" },
  { floor: "6F", number: 39, name: "mosco 모 스 코" },
  { floor: "6F", number: 43, name: "노 픈" },
  { floor: "6F", number: 44, name: "유 아 이 랩" },
  { floor: "6F", number: 45, name: "센 시 즈 (560565)" },
  { floor: "6F", number: 46, name: "아 일 스 테 이 지" },
  { floor: "6F", number: 48, name: "이 639( 클 리 어" },
  { floor: "6F", number: 49, name: "前 0](pair﹚" },
  { floor: "6F", number: 50, name: "가 더 667168" },
  { floor: "6F", number: 51, name: "by attention(H}0] 어 텐 션 )" },
  { floor: "7F", number: 4, name: "프 리 텐 더" },
  { floor: "7F", number: 5, name: "And More 앤 드 모 어" },
  { floor: "7F", number: 6, name: "ADEN 아 덴" },
  { floor: "7F", number: 7, name: "쿼 드 에 이" },
  { floor: "7F", number: 12, name: "LAINE" },
  { floor: "7F", number: 13, name: "H| 入 (vass﹚", uncertain: true },
  { floor: "7F", number: 14, name: "레 이 크 루 이 스" },
  { floor: "7F", number: 16, name: "50306 스 페 이 스" },
  { floor: "7F", number: 17, name: "파 머 스 마 켓" },
  { floor: "7F", number: 18, name: "12 게 이 지" },
  { floor: "7F", number: 19, name: "칼 레 이 도 스 코 프" },
  { floor: "7F", number: 20, name: "LeA 20}" },
  { floor: "7F", number: 21, name: "노 스 터" },
  { floor: "7F", number: 22, name: "로 비" },
  { floor: "7F", number: 23, name: "INDIGO ( 인 디 고 )" },
  { floor: "7F", number: 24, name: "콘 크 리트" },
  { floor: "7F", number: 27, name: "하 바 나" },
  { floor: "7F", number: 28, name: "요 코" },
  { floor: "7F", number: 29, name: "에 녹 ENOC" },
  { floor: "7F", number: 30, name: "헤 든 앤 미 로" },
  { floor: "7F", number: 34, name: "아 케 인" },
  { floor: "7F", number: 35, name: "run 引" },
  { floor: "7F", number: 36, name: "SENNE 센 느" },
  { floor: "7F", number: 37, name: "공 구 육 비" },
  { floor: "7F", number: 38, name: "promenade 프 롬 나 드" },
  { floor: "7F", number: 41, name: "르 젯" },
  { floor: "7F", number: 42, name: "엘 비 티 ( 리 베 르 떼 )" },
  { floor: "7F", number: 43, name: "에 이 바 이 엠" },
  { floor: "7F", number: 44, name: "TAKE 테 이크" },
  { floor: "7F", number: 45, name: "0| 刈 畜 (OUR ROOM﹚", uncertain: true },
  { floor: "7F", number: 46, name: "TATEMODERN8 테 이 트 모 던8" },
];

// Total: 304