// Auto-extracted from nuzzon.mp4 via ffmpeg + tesseract(kor+eng)
// 部分名称为 OCR 结果，可能需人工核对。

export type NuzzonShop = {
  floor: string; // B1 / 1F / 2F / ... / 6F
  number: number;
  name: string;
};

export const NUZZON_SHOPS: NuzzonShop[] = [
  // ===== B1 =====
  { floor: "B1", number: 1, name: "FL| JJUNY" },
  { floor: "B1", number: 10, name: "라 프" },
  { floor: "B1", number: 11, name: "라 프" },
  { floor: "B1", number: 16, name: "위 어" },
  // ===== 1F =====
  { floor: "1F", number: 100, name: "러 블 리" },
  { floor: "1F", number: 101, name: "비 앤 비" },
  { floor: "1F", number: 102, name: "태 리" },
  { floor: "1F", number: 103, name: "나 라" },
  { floor: "1F", number: 104, name: "마 이 턴" },
  { floor: "1F", number: 105, name: "딜 리" },
  { floor: "1F", number: 106, name: "인 터 뷰" },
  { floor: "1F", number: 107, name: "카 포" },
  { floor: "1F", number: 108, name: "아 로 하" },
  { floor: "1F", number: 109, name: "원 투 원 투" },
  { floor: "1F", number: 110, name: "알 키 미 스 트" },
  { floor: "1F", number: 111, name: "soojung 최 수 정" },
  { floor: "1F", number: 112, name: "style 8 ( 스 타 일 비 )" },
  { floor: "1F", number: 113, name: "바 이 더 스 타" },
  { floor: "1F", number: 114, name: "스 테 디" },
  { floor: "1F", number: 115, name: "빅 샤" },
  { floor: "1F", number: 116, name: "썸 바 인" },
  { floor: "1F", number: 117, name: "제 이 마 리 오" },
  { floor: "1F", number: 118, name: "포 커스" },
  { floor: "1F", number: 119, name: "APOLLO 아 폴 로" },
  { floor: "1F", number: 120, name: "피 프" },
  { floor: "1F", number: 121, name: "리 프" },
  { floor: "1F", number: 122, name: "모 다 지 오" },
  { floor: "1F", number: 123, name: "루 디 아" },
  { floor: "1F", number: 124, name: "미 미 룸" },
  { floor: "1F", number: 125, name: "메 테 리 얼" },
  { floor: "1F", number: 126, name: "오 르 트" },
  { floor: "1F", number: 127, name: "백 스 테 이 지" },
  { floor: "1F", number: 128, name: "하 다" },
  { floor: "1F", number: 129, name: "망 고" },
  { floor: "1F", number: 130, name: "드 리 프" },
  { floor: "1F", number: 131, name: "언 토" },
  { floor: "1F", number: 132, name: "동 대 문 몰 ( 카 시 오 )" },
  { floor: "1F", number: 133, name: "폭 스 힐" },
  { floor: "1F", number: 134, name: "메 르 시 보 꾸 ( ㅁ 라 이 66240040)" },
  // ===== 2F =====
  { floor: "2F", number: 201, name: "베 이직" },
  { floor: "2F", number: 202, name: "페 이 지" },
  { floor: "2F", number: 203, name: "아 오 스" },
  { floor: "2F", number: 204, name: "어 토이" },
  { floor: "2F", number: 205, name: "소 피 아" },
  { floor: "2F", number: 206, name: "ELYSIA 엘 리 시 아" },
  { floor: "2F", number: 207, name: "쿠 스 비" },
  { floor: "2F", number: 208, name: "Tomas club 토 마 스 클 럽" },
  { floor: "2F", number: 209, name: "상 우" },
  { floor: "2F", number: 210, name: "자 브" },
  { floor: "2F", number: 211, name: "메 조" },
  { floor: "2F", number: 212, name: "이 즈 니" },
  { floor: "2F", number: 213, name: "루 브 르" },
  { floor: "2F", number: 214, name: "인 디 오" },
  { floor: "2F", number: 215, name: "alife 에 이 라 이프" },
  { floor: "2F", number: 216, name: "오 드 오 즈" },
  { floor: "2F", number: 217, name: "로 프" },
  { floor: "2F", number: 218, name: "라 잇" },
  { floor: "2F", number: 219, name: "히 트" },
  { floor: "2F", number: 220, name: "tera 테 라" },
  { floor: "2F", number: 221, name: "왕 창 사" },
  { floor: "2F", number: 222, name: "아 베 크 디 자 인 (4/60.809190)" },
  { floor: "2F", number: 223, name: "보 니 타" },
  { floor: "2F", number: 224, name: "뉴 윙" },
  { floor: "2F", number: 225, name: "노 바 (404)" },
  { floor: "2F", number: 226, name: "로 그" },
  { floor: "2F", number: 227, name: "LUMINOUS 루 미 너 스" },
  { floor: "2F", number: 228, name: "비 케 이" },
  { floor: "2F", number: 229, name: "노 아" },
  { floor: "2F", number: 230, name: "엘 샤 다이" },
  { floor: "2F", number: 231, name: "Fitbow 핏 보 우" },
  { floor: "2F", number: 232, name: "스 토리" },
  // ===== 3F =====
  { floor: "3F", number: 301, name: "마 그 마" },
  { floor: "3F", number: 302, name: "에 피" },
  { floor: "3F", number: 303, name: "나 무" },
  { floor: "3F", number: 304, name: "고 릴 라" },
  { floor: "3F", number: 305, name: "이 슈" },
  { floor: "3F", number: 306, name: "VooShop 부샵" },
  { floor: "3F", number: 307, name: "가 니 쉬" },
  { floor: "3F", number: 308, name: "힐 스" },
  { floor: "3F", number: 309, name: "몬 드" },
  { floor: "3F", number: 310, name: "주 니" },
  { floor: "3F", number: 311, name: "포 트" },
  { floor: "3F", number: 312, name: "5 번 가" },
  { floor: "3F", number: 313, name: "sugarjeans 슈 가 진" },
  { floor: "3F", number: 314, name: "와 드" },
  { floor: "3F", number: 315, name: "00 하 니" },
  { floor: "3F", number: 316, name: "데데" },
  { floor: "3F", number: 317, name: "인 디 에 나" },
  { floor: "3F", number: 318, name: "와 이 진" },
  { floor: "3F", number: 319, name: "어 웨 이 브" },
  { floor: "3F", number: 320, name: "아 워" },
  { floor: "3F", number: 321, name: "킴 스" },
  { floor: "3F", number: 322, name: "누 티 지" },
  { floor: "3F", number: 323, name: "윈 썸" },
  { floor: "3F", number: 324, name: "바 니" },
  { floor: "3F", number: 325, name: "malenkii 말 렌 키" },
  { floor: "3F", number: 326, name: "매 러" },
  { floor: "3F", number: 327, name: "유 피 프 로 젝 트" },
  { floor: "3F", number: 328, name: "나 가 네" },
  { floor: "3F", number: 329, name: "벨 리 노" },
  // ===== 4F =====
  { floor: "4F", number: 401, name: "마 일 로" },
  { floor: "4F", number: 402, name: "화 이 트 샵" },
  { floor: "4F", number: 403, name: "런 던 프 리" },
  { floor: "4F", number: 404, name: "플 로 우 드" },
  { floor: "4F", number: 405, name: "레 어" },
  { floor: "4F", number: 406, name: "루 머" },
  { floor: "4F", number: 407, name: "베 어 리" },
  { floor: "4F", number: 408, name: "비 손 강" },
  { floor: "4F", number: 409, name: "항 아리" },
  { floor: "4F", number: 410, name: "커브" },
  { floor: "4F", number: 411, name: "지 앤" },
  { floor: "4F", number: 412, name: "클 롭" },
  { floor: "4F", number: 413, name: "혹 시" },
  { floor: "4F", number: 414, name: "드 랍" },
  { floor: "4F", number: 415, name: "하 이 피 스" },
  { floor: "4F", number: 416, name: "위 시" },
  { floor: "4F", number: 417, name: "유투" },
  { floor: "4F", number: 418, name: "유 니 모 어" },
  { floor: "4F", number: 419, name: "MUTE 뮤 트" },
  { floor: "4F", number: 420, name: "ETHOS ( 에 토 스 )" },
  { floor: "4F", number: 421, name: "파 크 드 림" },
  { floor: "4F", number: 422, name: "더 블 비" },
  { floor: "4F", number: 423, name: "에 스 티 1017( 오 센 치 . 묵 찌 빠 )" },
  { floor: "4F", number: 424, name: "스 파 이 웨 어" },
  { floor: "4F", number: 425, name: "바 넷" },
  { floor: "4F", number: 426, name: "000 예 원" },
  { floor: "4F", number: 427, name: "수 윤 ( 아 이 캔 )" },
  { floor: "4F", number: 428, name: "앤 드" },
  { floor: "4F", number: 429, name: "버 킷 리 스 트" },
  // ===== 5F =====
  { floor: "5F", number: 501, name: "헤 라" },
  { floor: "5F", number: 502, name: "standby 스 텐 바 이" },
  { floor: "5F", number: 503, name: "플 러 팅" },
  { floor: "5F", number: 504, name: "무전" },
  { floor: "5F", number: 505, name: "가 부 끼 수 제 화" },
  { floor: "5F", number: 506, name: "원 트" },
  { floor: "5F", number: 507, name: "가 람" },
  { floor: "5F", number: 508, name: "미 자 씨" },
  { floor: "5F", number: 509, name: "에 코" },
  { floor: "5F", number: 510, name: "month 먼 스" },
  { floor: "5F", number: 511, name: "후 디" },
  { floor: "5F", number: 512, name: "Asterr 아 스 터" },
  { floor: "5F", number: 513, name: "MiYa 미 야" },
  { floor: "5F", number: 514, name: "이 지" },
  { floor: "5F", number: 515, name: "리 턴 (Return)" },
  { floor: "5F", number: 516, name: "비 올 렌" },
  { floor: "5F", number: 517, name: "0010 첼 로" },
  { floor: "5F", number: 518, name: "03600 파 블 로" },
  { floor: "5F", number: 519, name: "발 렌 티" },
  { floor: "5F", number: 520, name: "세 기 모 자" },
  { floor: "5F", number: 521, name: "위 트 앤 원 더" },
  { floor: "5F", number: 522, name: "Flows 플 로 우 즈" },
  { floor: "5F", number: 523, name: "샤 인" },
  { floor: "5F", number: 524, name: "밀 크 쉐 이크" },
  { floor: "5F", number: 525, name: "리 브" },
  { floor: "5F", number: 526, name: "키 위" },
  { floor: "5F", number: 527, name: "라 인 업" },
  { floor: "5F", number: 528, name: "애 드 너 스" },
  { floor: "5F", number: 529, name: "제 이 케 이" },
  { floor: "5F", number: 530, name: "나 라라" },
  { floor: "5F", number: 531, name: "AEF (star gir)" },
  // ===== 6F =====
  { floor: "6F", number: 601, name: "오 페 라" },
  { floor: "6F", number: 602, name: "트 리거" },
  { floor: "6F", number: 603, name: "티 나" },
  { floor: "6F", number: 604, name: "별 무 리" },
  { floor: "6F", number: 605, name: "어 반 엘 로 우" },
  { floor: "6F", number: 606, name: "이 - 베 이 직 (6-84510)" },
  { floor: "6F", number: 607, name: "라 비 제이" },
  { floor: "6F", number: 608, name: "14/& ㅅ ( 자 바 )" },
  { floor: "6F", number: 609, name: "어 반 화 이 트" },
  { floor: "6F", number: 610, name: "모 인" },
  { floor: "6F", number: 611, name: "해 치" },
  { floor: "6F", number: 612, name: "에 버 모 어 (64@1 ㅁ 아리" },
  { floor: "6F", number: 613, name: "Weekend 위 켄 드" },
  { floor: "6F", number: 614, name: "다 온" },
  { floor: "6F", number: 615, name: "라 온" },
  { floor: "6F", number: 616, name: "아이" },
  { floor: "6F", number: 617, name: "콤 마" },
  { floor: "6F", number: 618, name: "영 이프" },
  { floor: "6F", number: 619, name: "시도" },
  { floor: "6F", number: 620, name: "bellescarpe 벨 레 스 카 르 페" },
  { floor: "6F", number: 621, name: "누 넬" },
  { floor: "6F", number: 622, name: "뉴 퀸" },
  { floor: "6F", number: 623, name: "미 애" },
  { floor: "6F", number: 624, name: "베 스 트 ( 더 킹 )" },
  { floor: "6F", number: 625, name: "selina 셀 리 나" },
  { floor: "6F", number: 626, name: "리 본" },
  { floor: "6F", number: 627, name: "피 터 팬" },
  { floor: "6F", number: 629, name: "시 스 터" },
  { floor: "6F", number: 630, name: "헤 이 걸" },
];

// 转换为统一 Shop 结构
import type { Shop } from "./mock-data";
export const NUZZON_AS_SHOPS: Shop[] = NUZZON_SHOPS.map((s) => ({
  id: `nuzzon-${s.floor}-${s.number}`,
  name: s.name,
  building: "NUZZON",
  floor: s.floor,
  position: String(s.number),
  tags: [],
  minOrderQty: 2,
  cover: `https://picsum.photos/seed/nuzzon-${s.floor}-${s.number}/320/200`,
  productCount: 0,
}));