/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopsIdRouteImport } from './routes/shops.$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as LogisticsIdRouteImport } from './routes/logistics.$id'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdRoute = ShopsIdRouteImport.update({
  id: '/shops/$id',
  path: '/shops/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIdRoute = LogisticsIdRouteImport.update({
  id: '/logistics/$id',
  path: '/logistics/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/me': typeof MeRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/shops/': typeof ShopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/me': typeof MeRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/shops': typeof ShopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/me': typeof MeRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/shops/': typeof ShopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/me'
    | '/logistics/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/shops/$id'
    | '/admin/'
    | '/orders/'
    | '/shops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/me'
    | '/logistics/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/shops/$id'
    | '/admin'
    | '/orders'
    | '/shops'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cart'
    | '/me'
    | '/logistics/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/shops/$id'
    | '/admin/'
    | '/orders/'
    | '/shops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  MeRoute: typeof MeRoute
  LogisticsIdRoute: typeof LogisticsIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ShopsIdRoute: typeof ShopsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id': {
      id: '/shops/$id'
      path: '/shops/$id'
      fullPath: '/shops/$id'
      preLoaderRoute: typeof ShopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/$id': {
      id: '/logistics/$id'
      path: '/logistics/$id'
      fullPath: '/logistics/$id'
      preLoaderRoute: typeof LogisticsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  MeRoute: MeRoute,
  LogisticsIdRoute: LogisticsIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  ShopsIdRoute: ShopsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
