/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PointsRulesRouteImport } from './routes/points-rules'
import { Route as PointsRouteImport } from './routes/points'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as MeRouteImport } from './routes/me'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as InviteRulesRouteImport } from './routes/invite-rules'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopsIdRouteImport } from './routes/shops.$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as PointsHistoryRouteImport } from './routes/points.history'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as LogisticsIdRouteImport } from './routes/logistics.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPointsMallRouteImport } from './routes/admin.points-mall'
import { Route as AdminPaymentAccountsRouteImport } from './routes/admin.payment-accounts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRulesRoute = PointsRulesRouteImport.update({
  id: '/points-rules',
  path: '/points-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRulesRoute = InviteRulesRouteImport.update({
  id: '/invite-rules',
  path: '/invite-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdRoute = ShopsIdRouteImport.update({
  id: '/shops/$id',
  path: '/shops/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsHistoryRoute = PointsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PointsRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIdRoute = LogisticsIdRouteImport.update({
  id: '/logistics/$id',
  path: '/logistics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/admin/stock',
  path: '/admin/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/admin/shops',
  path: '/admin/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/admin/shipping',
  path: '/admin/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPointsMallRoute = AdminPointsMallRouteImport.update({
  id: '/admin/points-mall',
  path: '/admin/points-mall',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentAccountsRoute = AdminPaymentAccountsRouteImport.update({
  id: '/admin/payment-accounts',
  path: '/admin/payment-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/discounts': typeof DiscountsRoute
  '/favorites': typeof FavoritesRoute
  '/groups': typeof GroupsRoute
  '/invite-rules': typeof InviteRulesRoute
  '/kyc': typeof KycRoute
  '/me': typeof MeRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/points': typeof PointsRouteWithChildren
  '/points-rules': typeof PointsRulesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-accounts': typeof AdminPaymentAccountsRoute
  '/admin/points-mall': typeof AdminPointsMallRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/users': typeof AdminUsersRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/points/history': typeof PointsHistoryRoute
  '/products/$id': typeof ProductsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/shops/': typeof ShopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/discounts': typeof DiscountsRoute
  '/favorites': typeof FavoritesRoute
  '/groups': typeof GroupsRoute
  '/invite-rules': typeof InviteRulesRoute
  '/kyc': typeof KycRoute
  '/me': typeof MeRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/points': typeof PointsRouteWithChildren
  '/points-rules': typeof PointsRulesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-accounts': typeof AdminPaymentAccountsRoute
  '/admin/points-mall': typeof AdminPointsMallRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/users': typeof AdminUsersRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/points/history': typeof PointsHistoryRoute
  '/products/$id': typeof ProductsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/shops': typeof ShopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/discounts': typeof DiscountsRoute
  '/favorites': typeof FavoritesRoute
  '/groups': typeof GroupsRoute
  '/invite-rules': typeof InviteRulesRoute
  '/kyc': typeof KycRoute
  '/me': typeof MeRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/points': typeof PointsRouteWithChildren
  '/points-rules': typeof PointsRulesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-accounts': typeof AdminPaymentAccountsRoute
  '/admin/points-mall': typeof AdminPointsMallRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/users': typeof AdminUsersRoute
  '/logistics/$id': typeof LogisticsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/points/history': typeof PointsHistoryRoute
  '/products/$id': typeof ProductsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/shops/': typeof ShopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/discounts'
    | '/favorites'
    | '/groups'
    | '/invite-rules'
    | '/kyc'
    | '/me'
    | '/new-arrivals'
    | '/points'
    | '/points-rules'
    | '/settings'
    | '/support'
    | '/admin/banners'
    | '/admin/config'
    | '/admin/feedback'
    | '/admin/groups'
    | '/admin/orders'
    | '/admin/payment-accounts'
    | '/admin/points-mall'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/shipping'
    | '/admin/shops'
    | '/admin/stock'
    | '/admin/users'
    | '/logistics/$id'
    | '/orders/$id'
    | '/points/history'
    | '/products/$id'
    | '/shops/$id'
    | '/admin/'
    | '/orders/'
    | '/shops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/discounts'
    | '/favorites'
    | '/groups'
    | '/invite-rules'
    | '/kyc'
    | '/me'
    | '/new-arrivals'
    | '/points'
    | '/points-rules'
    | '/settings'
    | '/support'
    | '/admin/banners'
    | '/admin/config'
    | '/admin/feedback'
    | '/admin/groups'
    | '/admin/orders'
    | '/admin/payment-accounts'
    | '/admin/points-mall'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/shipping'
    | '/admin/shops'
    | '/admin/stock'
    | '/admin/users'
    | '/logistics/$id'
    | '/orders/$id'
    | '/points/history'
    | '/products/$id'
    | '/shops/$id'
    | '/admin'
    | '/orders'
    | '/shops'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/discounts'
    | '/favorites'
    | '/groups'
    | '/invite-rules'
    | '/kyc'
    | '/me'
    | '/new-arrivals'
    | '/points'
    | '/points-rules'
    | '/settings'
    | '/support'
    | '/admin/banners'
    | '/admin/config'
    | '/admin/feedback'
    | '/admin/groups'
    | '/admin/orders'
    | '/admin/payment-accounts'
    | '/admin/points-mall'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/shipping'
    | '/admin/shops'
    | '/admin/stock'
    | '/admin/users'
    | '/logistics/$id'
    | '/orders/$id'
    | '/points/history'
    | '/products/$id'
    | '/shops/$id'
    | '/admin/'
    | '/orders/'
    | '/shops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DiscountsRoute: typeof DiscountsRoute
  FavoritesRoute: typeof FavoritesRoute
  GroupsRoute: typeof GroupsRoute
  InviteRulesRoute: typeof InviteRulesRoute
  KycRoute: typeof KycRoute
  MeRoute: typeof MeRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  PointsRoute: typeof PointsRouteWithChildren
  PointsRulesRoute: typeof PointsRulesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentAccountsRoute: typeof AdminPaymentAccountsRoute
  AdminPointsMallRoute: typeof AdminPointsMallRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LogisticsIdRoute: typeof LogisticsIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ShopsIdRoute: typeof ShopsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points-rules': {
      id: '/points-rules'
      path: '/points-rules'
      fullPath: '/points-rules'
      preLoaderRoute: typeof PointsRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-rules': {
      id: '/invite-rules'
      path: '/invite-rules'
      fullPath: '/invite-rules'
      preLoaderRoute: typeof InviteRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id': {
      id: '/shops/$id'
      path: '/shops/$id'
      fullPath: '/shops/$id'
      preLoaderRoute: typeof ShopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/history': {
      id: '/points/history'
      path: '/history'
      fullPath: '/points/history'
      preLoaderRoute: typeof PointsHistoryRouteImport
      parentRoute: typeof PointsRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/$id': {
      id: '/logistics/$id'
      path: '/logistics/$id'
      fullPath: '/logistics/$id'
      preLoaderRoute: typeof LogisticsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/admin/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/admin/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/admin/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/points-mall': {
      id: '/admin/points-mall'
      path: '/admin/points-mall'
      fullPath: '/admin/points-mall'
      preLoaderRoute: typeof AdminPointsMallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-accounts': {
      id: '/admin/payment-accounts'
      path: '/admin/payment-accounts'
      fullPath: '/admin/payment-accounts'
      preLoaderRoute: typeof AdminPaymentAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PointsRouteChildren {
  PointsHistoryRoute: typeof PointsHistoryRoute
}

const PointsRouteChildren: PointsRouteChildren = {
  PointsHistoryRoute: PointsHistoryRoute,
}

const PointsRouteWithChildren =
  PointsRoute._addFileChildren(PointsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DiscountsRoute: DiscountsRoute,
  FavoritesRoute: FavoritesRoute,
  GroupsRoute: GroupsRoute,
  InviteRulesRoute: InviteRulesRoute,
  KycRoute: KycRoute,
  MeRoute: MeRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  PointsRoute: PointsRouteWithChildren,
  PointsRulesRoute: PointsRulesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentAccountsRoute: AdminPaymentAccountsRoute,
  AdminPointsMallRoute: AdminPointsMallRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminStockRoute: AdminStockRoute,
  AdminUsersRoute: AdminUsersRoute,
  LogisticsIdRoute: LogisticsIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  ShopsIdRoute: ShopsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
